---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nts-pool.fullname" . }}-ke-config
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "nts-pool.labels" . | nindent 4 }}
data:
  pool.toml: |
    [server]
    listen = "[::]:4460"
    certificate-chain = "/opt/nts-pool/tls/tls.crt"
    private-key = "/opt/nts-pool/tls/tls.key"
    max-connections = {{ .Values.ke.maxConnections }}
    monitoring-keys = "/opt/nts-pool/monitoring/monitoring.json"
    use-proxy-protocol = {{ .Values.ke.useProxyProtocol }}

    [backend]
    allowed-protocols = [0]
    certificate-chain = "/opt/nts-pool/tls/tls.crt"
    private-key = "/opt/nts-pool/tls/tls.key"
    key-exchange-servers = "/opt/nts-pool/ke-servers/servers.json"
    base-shared-secret = "/opt/nts-pool/base-shared-secret/base-shared-secret.key"
