{{- if .Values.management.databaseCertificate.cert }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nts-pool.fullname" . }}-management-db-cert
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "nts-pool.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10" # run before the migrate job
data:
  db.pem: |
    {{- .Values.management.databaseCertificate.cert | nindent 4 }}
{{- end }}
