---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nts-pool.fullname" . }}-dns-config
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "nts-pool.labels" . | nindent 4 }}
data:
  pool.toml: |
    [zone]
    geolocation-db-path = "/opt/geodb/geodb.mmdb"
    zone-name = "{{ .Values.dns.poolDomain }}"
    dns-server-name = "{{ .Values.dns.nameserverDomain }}"
    responsible-name = "{{ .Values.dns.responsibleDomain }}"
    private-key-path = "/opt/nts-pool/dnssec/dnssec.key"
    servers-list-path = "/opt/nts-pool/servers/servers.json"

    [server]
    listen = "[::]:3453"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "nts-pool.fullname" . }}-dns
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "nts-pool.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: dns
      {{- include "nts-pool.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: dns
        {{- include "nts-pool.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: geolocation-script
          configMap:
            name: {{ include "nts-pool.fullname" . }}-geolocation-internal
            items:
              - key: "geolocation-loader.sh"
                path: "geolocation-loader.sh"
                mode: 0755
        - name: geolocation
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ include "nts-pool.fullname" . }}-dns-config
            items:
              - key: "pool.toml"
                path: "pool.toml"
        - name: servers-volume
          configMap:
            name: {{ include "nts-pool.fullname" . }}-servers-config
            items:
              - key: "servers.json"
                path: "servers.json"
        - name: dnssec-volume
          secret:
            secretName: {{ default (cat (include "nts-pool.fullname" .) "-dnssec") .Values.dns.dnssecSecretName }}
            items:
              - key: "dnssec.key"
                path: "dnssec.key"
      initContainers:
      - name: geolocation
        imagePullPolicy: "{{ default .Values.image.pullPolicy .Values.management.image.pullPolicy }}"
        {{- with default .Values.image.pullSecrets .Values.management.image.pullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ default .Values.image.repository .Values.management.image.repository }}:{{ default .Values.image.tag .Values.management.image.tag }}"
        command: ["/opt/geodb/scripts/geolocation-loader.sh"]
        workingDir: "/opt/geodb/"
        volumeMounts:
          - name: geolocation
            mountPath: "/opt/geodb"
          - name: geolocation-script
            mountPath: "/opt/geodb/scripts/"
            readOnly: true
        restartPolicy: Always
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - test -e /opt/geodb/geodb.mmdb
        env:
          - name: URL
            value: "http://{{ include "nts-pool.fullname" . }}-geodb-cache.{{ default .Release.Namespace .Values.namespaceOverride }}.svc.{{ .Values.clusterDomain }}/geodb.mmdb"
          - name: TARGET
            value: "/opt/geodb/geodb.mmdb"
          - name: PERIOD
            value: "24h"
      containers:
      - name: dns
        imagePullPolicy: "{{ default .Values.image.pullPolicy .Values.dns.image.pullPolicy }}"
        {{- with default .Values.image.pullSecrets .Values.dns.image.pullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ default .Values.image.repository .Values.dns.image.repository }}:{{ default .Values.image.tag .Values.dns.image.tag }}"
        command: ["/usr/local/bin/nts-pool-dns", "-c", "/opt/nts-pool/config/pool.toml", "-l", "trace"]
        workingDir: "/opt/nts-pool"
        ports:
          - containerPort: 3453
            protocol: UDP
            name: dns-udp
          - containerPort: 3453
            protocol: TCP
            name: dns-tcp
        volumeMounts:
          - name: geolocation
            mountPath: "/opt/geodb"
          - name: config-volume
            mountPath: /opt/nts-pool/config
            readOnly: true
          - name: servers-volume
            mountPath: /opt/nts-pool/servers
            readOnly: true
          - name: dnssec-volume
            mountPath: /opt/nts-pool/dnssec
            readOnly: true
        env:
          - name: RESTART_BUMP
            value: "{{ default 1 .Values.dns.restartBump}}"
          - name: OTEL_METRICS_EXPORT_DESTINATION
            value: "{{ .Values.metrics.endpoint }}"
          {{- with .Values.metrics.headerSecretRef }}
          - name: OTEL_EXPORTER_OTLP_METRICS_HEADERS
            valueFrom:
              secretKeyRef:
                {{- toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.dns.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nts-pool.fullname" . }}-dns
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "nts-pool.labels" . | nindent 4 }}
  {{- with .Values.services.dns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.dns.type }}
  externalTrafficPolicy: Local
  ipFamilyPolicy: "PreferDualStack"
  {{- if and (eq .Values.services.dns.type "LoadBalancer") .Values.services.dns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.services.dns.loadBalancerIP }}
  {{- end }}
  selector:
    app.kubernetes.io/component: dns
    {{- include "nts-pool.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.services.dns.port }}
    targetPort: 3453
    protocol: UDP
    name: dns-udp
  - port: {{ .Values.services.dns.port }}
    targetPort: 3453
    protocol: TCP
    name: dns-tcp
