---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nts-pool.fullname" . }}-management
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "nts-pool.labels" . | nindent 4 }}
  {{- with .Values.services.management.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: management
    {{- include "nts-pool.selectorLabels" . | nindent 4 }}
  ports:
  - port: 3000
    targetPort: 3000
    name: http
