# part of the test setup for the NTS pool KE. Do not use in production!
# (the private key of the certificate is public!)
[server]
listen = "0.0.0.0:4460"
certificate-chain = "./testdata/end.fullchain.pem"
private-key = "./testdata/end.key"
max-connections = 100
monitoring-keys = "./monitoring.json"

[backend]
upstream-cas = "./testdata/testca.pem"
allowed-protocols = [0]
certificate-chain = "./testdata/end.fullchain.pem"
private-key = "./testdata/end.key"
key-exchange-servers = "./servers.json"
base-shared-secret = "./base-shared-secret"
